-- Enable UUID
create extension if not exists "uuid-ossp";

-- Table: Profiles (Roles)
create table public.profiles (
  id uuid references auth.users not null primary key,
  email text,
  role text check (role in ('manager', 'seller')) default 'seller'
);

-- Table: Products
create table public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  code text unique not null,
  category text,
  brand text,
  price numeric not null,
  promo_price numeric,
  status text default 'active',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Table: Product Variants
create table public.product_variants (
  id bigint generated by default as identity primary key,
  product_id bigint references public.products on delete cascade,
  size text not null,
  color text not null,
  stock_quantity integer default 0,
  unique(product_id, size, color)
);

-- Table: Cash Registers
create table public.cash_registers (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  opening_balance numeric not null,
  closing_balance numeric,
  status text check (status in ('open', 'closed')) default 'open',
  opened_at timestamp with time zone default now(),
  closed_at timestamp with time zone,
  notes text
);

-- Table: Sales
create table public.sales (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  total numeric not null,
  discount numeric default 0,
  payment_method text not null,
  register_id bigint references public.cash_registers,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Table: Sale Items
create table public.sale_items (
  id bigint generated by default as identity primary key,
  sale_id bigint references public.sales on delete cascade,
  variant_id bigint references public.product_variants,
  quantity integer not null,
  price_at_sale numeric not null
);

-- Table: Cash Movements
create table public.cash_movements (
  id bigint generated by default as identity primary key,
  register_id bigint references public.cash_registers on delete cascade,
  type text check (type in ('sale', 'bleed', 'entry')),
  amount numeric not null,
  description text,
  created_at timestamp with time zone default now()
);

-- TRIGGER: Auto-create profile on signup
create or replace function public.handle_new_user() 
returns trigger as $$
begin
  insert into public.profiles (id, email, role)
  values (new.id, new.email, 'manager'); -- Default to manager for first user (seed) or change manually
  return new;
end;
$$ language plpgsql security definer;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- RPC: Complete Sale Transaction
create or replace function complete_sale(
  p_user_id uuid,
  p_total numeric,
  p_discount numeric,
  p_payment_method text,
  p_items jsonb,
  p_register_id bigint
) returns void as $$
declare
  v_sale_id bigint;
  item jsonb;
begin
  -- Insert Sale
  insert into public.sales (user_id, total, discount, payment_method, register_id)
  values (p_user_id, p_total, p_discount, p_payment_method, p_register_id)
  returning id into v_sale_id;

  -- Insert Items and Update Stock
  for item in select * from jsonb_array_elements(p_items) loop
    insert into public.sale_items (sale_id, variant_id, quantity, price_at_sale)
    values (v_sale_id, (item->>'variant_id')::bigint, (item->>'quantity')::int, (item->>'price_at_sale')::numeric);

    update public.product_variants
    set stock_quantity = stock_quantity - (item->>'quantity')::int
    where id = (item->>'variant_id')::bigint;
  end loop;

  -- Update Cash Movement
  insert into public.cash_movements (register_id, type, amount, description)
  values (p_register_id, 'sale', p_total, 'Venda #' || v_sale_id);
end;
$$ language plpgsql;

-- SEED DATA
insert into public.products (name, code, category, brand, price) values 
('Camiseta Básica', 'CAM001', 'Camisetas', 'Hering', 49.90),
('Calça Jeans Slim', 'JEANS01', 'Calças', 'Levis', 199.90),
('Vestido Floral', 'VEST001', 'Vestidos', 'Zara', 129.90);

insert into public.product_variants (product_id, size, color, stock_quantity) values
(1, 'M', 'Preto', 10),
(1, 'G', 'Preto', 5),
(1, 'M', 'Branco', 8),
(2, '40', 'Jeans', 15),
(2, '42', 'Jeans', 12),
(3, 'P', 'Vermelho', 3);
